[build]
  publish = "dist"  # Adjust to your build folder
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
